/*
 * generated by Xtext 2.19.0
 */
package bergmann.masterarbeit.mappingdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MappingDSLRuntimeModule extends AbstractMappingDSLRuntimeModule {
}
