/*
 * generated by Xtext 2.19.0
 */
package bergmann.masterarbeit.mappingdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MappingDSLStandaloneSetup extends MappingDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MappingDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
