/*
 * generated by Xtext 2.12.0
 */
package bergmann.masterarbeit.mappingdsl.tests

import bergmann.masterarbeit.mappingdsl.mappingDSL.Domain
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MappingDSLInjectorProvider)
class MappingDSLParsingTest {
	@Inject
	ParseHelper<Domain> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
