/*
 * generated by Xtext 2.12.0
 */
package bergmann.masterarbeit


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MonitorDslStandaloneSetup extends MonitorDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MonitorDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
