/*
 * generated by Xtext 2.12.0
 */
package bergmann.masterarbeit.mappingdsl.ide


/**
 * Use this class to register ide components.
 */
class MappingDSLIdeModule extends AbstractMappingDSLIdeModule {
}
