/*
 * generated by Xtext 2.19.0
 */
package bergmann.masterarbeit.monitordsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MonitorDSLStandaloneSetup extends MonitorDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MonitorDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
