/*
 * generated by Xtext 2.19.0
 */
package bergmann.masterarbeit.monitordsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import bergmann.masterarbeit.monitordsl.monitorDSL.Monitors

@ExtendWith(InjectionExtension)
@InjectWith(MonitorDSLInjectorProvider)
class MonitorDSLParsingTest {
	@Inject
	ParseHelper<Monitors> parseHelper
	
	@Test
	def void loadMonitors() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
