/*
 * generated by Xtext 2.19.0
 */
package bergmann.masterarbeit.monitordsl.ide


/**
 * Use this class to register ide components.
 */
class MonitorDSLIdeModule extends AbstractMonitorDSLIdeModule {
}
